# Generated by Django 6.0.5 on 2026-05-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('branch', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
                ('college', models.CharField(max_length=100)),
            ],
        ),
    ]
